version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: crypgo
      POSTGRES_PASSWORD: crypgo
      POSTGRES_DB: crypgo_machine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: crypgo_test
      POSTGRES_PASSWORD: crypgo_test
      POSTGRES_DB: crypgo_machine_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
  postgres_test_data:
